Fix py CI
When running the CI with python 3.9 there's an issue ([1]):

    reorder-python-imports --py3-plus --separate-from-import --separate-relative --diff-only reddit_edgecontext/thrift/constants.py reddit_edgecontext/thrift/ttypes.py reddit_edgecontext/thrift/__init__.py reddit_edgecontext/__init__.py tests/edge_context_tests.py setup.py
    black --diff --check reddit_edgecontext/thrift/constants.py reddit_edgecontext/thrift/ttypes.py reddit_edgecontext/thrift/__init__.py reddit_edgecontext/__init__.py tests/edge_context_tests.py setup.py
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.9.10/x64/bin/black", line 5, in <module>
        from black import patched_main
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/black/__init__.py", line 52, in <module>
        from typed_ast import ast3, ast27
      File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/typed_ast/ast3.py", line 40, in <module>
        from typed_ast import _ast3
    ImportError: /opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_DecodeUnicodeEscape
    make: *** [Makefile:20: lint] Error 1

This is caused by the pinned typed-ast version being too old. But
bumping typed-ast also requires us to bump the version of mypy and
typing-extensions as well, and also there's not a version of typed-ast
that works for both python 3.7 and python 3.9.

So bump versions of mypy and typing-extensions to the same version as
baseplate.py, and unpin typed-ast to support both 3.7 and 3.9.

Also update python version to 3.9 in Dockerfile.

[1]: https://github.com/reddit/edgecontext/runs/5562917588?check_suite_focus=true